### ISSUE TITLE
Relation between Connection and IncomingStreams

### ISSUE THREAD

**Issue by ustulation** [djc/quinn#250]
On a successful connection in either direction (i.e., either actively via connect or passively via listen) I get two things eventually - one `Connection` and one `IncomingStreams`. As a user i expect these to be related at some level since they denote _a_ connection to the peer. However it seems that closing the connection does nothing for the `IncomingStreams`.

Details:

0. I get a `Connection` and `IncomingStreams` from a peer while I'm listening
1. Something happens and I decide I don't want this peer any more
2. I get the `Connection` object and do `Connection::close(...)`.
3. Nothing happens to the `IncomingStreams` - it continue to stay indefinitely with tokio event loop - I would have expected it to resolve to completion/failure at this point and destroy itself.
4. Remote peer still tries to send something to us on their connection to us (Which is still alive for them) by trying to open a new stream to us. The peer keeps getting "ConnectionAborted - closed by remote peer" error which is fine and expected.

So the `IncomingStreams` stream (and possibly any other stream obtained from it which the remote hasn't shutdown/closed/destroyed yet - though I haven't checked this part) uselessly remains unresolved with tokio. I have to now keep extra knowledge about closing these streams when I close the `Connection` to the peer.

Wouldn't the better/expected design be that when I close `Connection` (or drop/destroy it) all the related stuff resolve into an error (or anything, but resolve) to gracefully collect all resources ?

**Comment by djc** [comment]
Yup, that seems like an oversight we should fix. Do you want to try a PR? We probably want a `dropped` flag in `ConnectionInner` similar to the one in `EndpointInner`; if `IncomingStreams` is polled and `dropped` is true, it should probably return `Ready(None)`.

**Comment by ustulation** [comment]
Is the `IncomingStreams` definitely notified when the drop flag is set ? Otherwise could be quite a while between the drop flag being set and when the stream is polled (which will probably be when the remote tries opening one to us making us be at the mercy of the remote peer). If that's true, maybe have IncomingStreams pass through a `select` (some stream or future selector) first which selects  `IncomingStreams` or `Blah` (whatever we name it) with `Blah` being a type that gets notified when something fires on drop and then resolves to `Ready(None)` or `Err` or whatever. E.g, `Blah` could be a oneshot or mpsc rx or something custom atop it or whatever makes sense

**Comment by djc** [comment]
When the `dropped` flag is set, we should likely also notify the `pending.incoming_streams_reader`.

Note that a lot of this code will be overhauled soon, to the effect that `ConnectionInner`s will no longer hold a reference to the `EndpointInner`, but will instead own a `quinn::Connection` and have some channels to facilitate communication between endpoint and connection.

**Comment by Ralith** [comment]
This (and #252) is intended to be handled by the connection emitting `ConnectionLost` once it has been closed, causing `Pending::fail` to be called, which wakes up all blocked streams. However, on review, we only seem to do this when the peer explicitly acknowledges the close, which is optional and something we don't even do ourselves. I'll draft a fix tonight.

**Comment by Ralith** [comment]
This, #251, and #252 should be fixed as of #271, if not earlier. Can you confirm?

**Comment by ustulation** [comment]
hmm i tested #251 with commit https://github.com/djc/quinn/commit/e9b9a3861b9c26417d93757a673354cf6de11b9d in master and dropping connection still doesn't close it. I tried to see what the dtor of `ConnectionRef` (as that's probably going to be called when I drop the `Connection`) does and this:
https://github.com/djc/quinn/blob/aae9edecd48e5bc0e3b5ff1e8d328cd42b55a6ad/quinn/src/connection.rs#L272
happens to be 4 or something so probably since it's shared with `IncomingStreams` and other stuff, the ref count actually never reaches the correct value to trigger a close ?

However if i explicitly call close on it (which now seems to consume `Connection`): https://github.com/djc/quinn/blob/aae9edecd48e5bc0e3b5ff1e8d328cd42b55a6ad/quinn/src/connection.rs#L180
then yes, the `IncomingStreams` and all children streams waiting in `read_to_end` are resolved. So that issue is perhaps fixed now.

Also while testing i now see random panics from quinn when i explicit call close(). I cannot produce these in debug so my backtrace is probably useless but here's the relevant section:
```
 8: core::result::unwrap_failed
  9: <quinn::endpoint::Driver as futures::future::Future>::poll
 10: <futures::future::map_err::MapErr<A, F> as futures::future::Future>::poll
```
The panic is on some send-error:
```panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")'```

Just putting here for convenience but if you want i can open a separate issue.

**Comment by djc** [comment]
The intention is that the connection will only be closed when both the `Connection` **and** the `IncomingStreams` are dropped -- otherwise you might still be using the connection through the other. And you might still have more references through any streams that were already open. In other words, if you intentionally want to close the connection, dropping is not enough -- but if all references that would allow you to use the connection go away, it should be implicitly closed.

**Comment by ustulation** [comment]
> In other words, if you intentionally want to close the connection, dropping is not enough

that contradicts the documentation a bit though:
https://github.com/djc/quinn/blob/aae9edecd48e5bc0e3b5ff1e8d328cd42b55a6ad/quinn/src/connection.rs#L121
Or at-least makes it a bit confusing in the context.

I think (but not surely ofc) there could be a better approach though. Is it because the design that we are constrained - perhaps because we are mismanaging ownership or using smart-pointers in-appropriately ? Just a braindump but could we have restricted the ownership to just say the `Connection` (since that's what the doc implies) and the rest have weak-ptrs instead of cloning strong-ptrs and making it ownership nightmare ? I find logic based on ref-counts to be fragile as that's what it's ("smart" ptrs) meant to abstract - otherwise we might have as well used raw-ptrs and done the bookkeeping.

`/IncomingStreams` is not something one is holding on to manually - it's spawned into the event loop and forgotten. The "handle" is the `Connection` and that is all that should count.

**Comment by ustulation** [comment]
So the semantics seems (from reading the docs) similar to `mpsc::Sender` where if you drop the last copy of the `Sender` it causes the rx to exit (with error in most cases and with an `Ok` for `tokio::..::watch`)

Also the caveat on depending on ref-counts: https://doc.rust-lang.org/std/sync/struct.Arc.html#method.strong_count and in [c++ too](https://en.cppreference.com/w/cpp/memory/shared_ptr/use_count) which is probably worse due to relaxed loading instead of seq-cst as in Rust:
> the value returned by use_count is approximate (typical implementations use a memory_order_relaxed load) 

So it seems to be a fragile design, but ofc this might be the best in the given context - just that managing logic depending on ref-count seems a little niche :)

**Comment by djc** [comment]
Hmm, not sure. `IncomingStreams` is not spawned into the event loop, actually -- that's `ConnectionDriver`, and that's account for (it's why we check for reference count == 2). The semantics we were going for is that if you're holding any reference into the `ConnectionInner` that you can actually still use, we don't want to close the `Connection` implicitly. Conversely, we find it reasonable if you drop the `Connection` but hold on to the `IncomingStreams`, for example for server connections, and in that case clearly the connection should not be dropped.

**Comment by djc** [comment]
> So it seems to be a fragile design, but ofc this might be the best in the given context - just that managing logic depending on ref-count seems a little niche :)

This case seems to be a relatively safe. If the count == 2 inside a `Drop`, that means it's about to be reduced to 1 -- which should really always be the `ConnectionDriver`. Since we're returning a triple of `ConnectionRef` owners when the connection is established, that seems unlikely to happen in any other case unless the `ConnectionDriver` is not spawned correctly, which we should maybe more clearly document as user error.

**Comment by ustulation** [comment]
> not sure. IncomingStreams is not spawned into the event loop

By spawned into the event loop i mean it's consumed, converted into some leaf future and then spawned - so basically it's gone while the `Connection` remains as a handle. You can drop that to drop all incoming as well as outgoing stuff. Otherwise it's contradictory that `Connection::close()` then causes `IncomingStreams` and all it's children streams to exit.

**Comment by djc** [comment]
You haven't convinced me yet that the current design is bad, although I would agree it needs better/clearer documentation!

**Comment by ustulation** [comment]
> You haven't convinced me yet that the current design is bad

np, i'm fine using it the way it is - to me it appears to have more maintenance hassle in future tracking ref-count and all - but that might be just me.

> We really wanted to support the case of dropping the Connection but holding on to the IncomingStreams, for example for server connections

This part is confusing me a bit from usability perspective. `Connection::close()` does affect other things - if it affected only outgoing streams (e.g, write_to_end or open_bi/uin etc., resolved on its destruction/closure) then yes they are orthogonal and have to be managed separately. But on one hand we have something like a handle when we call close on, it is consumed and closes everything even the incoming stuff which it did not have to do anything with, on the other we are saying that we could drop the last copy of the `Connection` which also consuming it (well dropping is consuming) without it affecting everything, but just the outgoing.

**Comment by djc** [comment]
Yes, that's exactly right:

- Implicitly dropping things does not close the `Connection` until all the references into it are dropped, there is no explicit intent to close the connection
- Explicitly closing will error out all references into it, because the user has communicated their intent to trigger that

**Comment by ustulation** [comment]
OK will use it that way then.

> mplicitly dropping things does not close the Connection until all the references into it are dropped, there is no explicit intent to close the connection

Bit strange to the user as they don't care about the "references into it" - they just care about how many copies of `Connection` they have since that's what they see.

Anyhoo, just so that the other [issue with panic](https://github.com/djc/quinn/issues/250#issuecomment-478572701) doesn't get lost in this discussion. Let me know if you want a separate issue for that one.

**Comment by djc** [comment]
We think it would be strange if `IncomingStreams` would error out just because you dropped `Connection`, or alternatively, that it would be useful to be able to use `IncomingStreams` without holding on to `Connection`.

Probably good to file another issue for the panic!

**Comment by Ralith** [comment]
The implicit close semantics are intended. In particular, it is necessary for this to work:
```rust
incoming_connections.for_each(|(driver, conn, streams)| {
    runtime.spawn(driver);
    runtime.spawn(streams.for_each(handle_request));
});
```
Note that the `Connection` handle is dropped immediately, but the user's intent is clearly to continue invoking `handle_request` on incoming streams until the peer closes the connection. By contrast, calling `close` expresses the intention that the entire connection should be immediately interrupted.

> Also the caveat on depending on ref-counts: https://doc.rust-lang.org/std/sync/struct.Arc.html#method.strong_count and in c++ too which is probably worse due to relaxed loading instead of seq-cst as in Rust:

I think you've caught a subtle bug here, thanks! In particular, if two separate threads drop a `ConnectionRef` or `EndpointRef` simultaneously, and there are initially three references, then it is possible for neither to observe it reaching 2 references, so the implicit close will not take place. We can probably fix this by locking the connection's/endpoint's mutex before inspecting the count, thereby forcibly linearizing drops.

**Comment by ustulation** [comment]
I'm happy to close this now as i can see all stuff regarding and spawning from this are resolved (at-least in my tests), or the admins can close it later if they think they need to work on this more somewhere.

**Comment by Ralith** [comment]
We believe this to be solved, and if your tests are passing, that's good confirmation; thanks!
