### ISSUE TITLE
Code coverage is broken

### ISSUE THREAD

**Issue by djc** [djc/quinn#336]
Apparently broken because of https://github.com/rust-lang/rust/issues/58375, and we failed to notice for a long time because of https://github.com/xd009642/tarpaulin/issues/219 (despite changes in #286 so far).

**Comment by Ralith** [comment]
Has this been fixed by the move to azure pipelines?

**Comment by djc** [comment]
The rustc has finally been fixed in Nightly this week, this is now pending https://github.com/crate-ci/azure-pipelines/pull/42 so we can run the coverage on nightly until the fix gets to stable.

**Comment by djc** [comment]
Still not quite working, need to get https://github.com/xd009642/tarpaulin/issues/239.

**Comment by djc** [comment]
In the ongoing saga, that issue has now been fixed but we appear to be running into (a variant of) https://github.com/xd009642/tarpaulin/issues/190 now.

**Comment by stammw** [comment]
This issue can now be closed I guess ?

**Comment by djc** [comment]
Yes, at least this particular cause is no longer relevant.
