### ISSUE TITLE
Integer overflow running benchmark

### ISSUE THREAD

**Issue by alecmocatta** [djc/quinn#639]
Running a minimally changed version of https://github.com/djc/quinn/blob/605c9a57efd89055118232fbb9eee3728e68ffbb/quinn/benches/bench.rs, in release mode with `overflow-checks = true`, triggers integer overflow here:

https://github.com/djc/quinn/blob/605c9a57efd89055118232fbb9eee3728e68ffbb/quinn-proto/src/assembler.rs#L128

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', /Users/alecmocatta/.cargo/git/checkouts/quinn-572d2e5812b43165/605c9a5/quinn-proto/src/assembler.rs:128:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /Users/alecmocatta/.cargo/git/checkouts/quinn-572d2e5812b43165/605c9a5/quinn/src/connection.rs:500:26
stack backtrace:
   0:        0x10828236f - backtrace::backtrace::libunwind::trace::hcfa7701d6c81f8a0
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:        0x10828236f - backtrace::backtrace::trace_unsynchronized::h779bbcc9c02b9355
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:        0x10828236f - std::sys_common::backtrace::_print_fmt::habf57f6a558eac94
                               at src/libstd/sys_common/backtrace.rs:78
   3:        0x10828236f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc660489926238a51
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10829b39e - core::fmt::write::h85d7f7431aad7c6e
                               at src/libcore/fmt/mod.rs:1052
   5:        0x10827e3cb - std::io::Write::write_fmt::hea8e7fea3b67f600
                               at src/libstd/io/mod.rs:1428
   6:        0x10828426a - std::sys_common::backtrace::_print::h8291258e26c6cac9
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10828426a - std::sys_common::backtrace::print::h9022c7942b3bfada
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10828426a - std::panicking::default_hook::{{closure}}::h594982c6a4b10b79
                               at src/libstd/panicking.rs:204
   9:        0x108283f92 - std::panicking::default_hook::hc433e2981735fb5f
                               at src/libstd/panicking.rs:224
  10:        0x1082848d8 - std::panicking::rust_panic_with_hook::heea00f89b45f5ac9
                               at src/libstd/panicking.rs:470
  11:        0x1082844a2 - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:        0x1082a9d1f - core::panicking::panic_fmt::he90b7accb40987e1
                               at src/libcore/panicking.rs:85
  13:        0x1082a9c25 - core::option::expect_none_failed::h1dce1765a6e65857
                               at src/libcore/option.rs:1211
  14:        0x108185a20 - core::result::Result<T,E>::unwrap::hd19ed174e2bc26a1
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/result.rs:1003
  15:        0x108185a20 - <quinn::connection::ConnectionRef as core::ops::drop::Drop>::drop::hc28a16f930a57c73
                               at /Users/alecmocatta/.cargo/git/checkouts/quinn-572d2e5812b43165/605c9a5/quinn/src/connection.rs:500
  16:        0x10816d0ca - core::ptr::drop_in_place::hf63a3652f375bdb6
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  17:        0x10816d0ca - core::ptr::drop_in_place::h8de588d8ca53b3d2
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  18:        0x10816d0ca - core::ptr::drop_in_place::hf88042267b8e179e
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  19:        0x10816d0ca - core::ptr::drop_in_place::he25e1680f2068a41
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ptr/mod.rs:174
  20:        0x10816d0ca - tokio::task::core::Core<T>::transition_to_consumed::h01876de0bf6bc76f
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/core.rs:106
  21:        0x10816747b - tokio::task::harness::Harness<T,S>::poll::{{closure}}::{{closure}}::haffc660f700161bc
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:126
  22:        0x10816747b - core::ops::function::FnOnce::call_once::h4b692cb3c3e83c6e
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ops/function.rs:232
  23:        0x10816747b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6b41556582c14c56
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:318
  24:        0x10816747b - std::panicking::try::do_call::h644839c70adebacb
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:303
  25:        0x10828716b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  26:        0x1081544b3 - std::panicking::try::h9c99218bffcf36f0
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:281
  27:        0x1081544b3 - std::panic::catch_unwind::h145d755f68975d9b
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:394
  28:        0x1081544b3 - tokio::task::harness::Harness<T,S>::poll::{{closure}}::h2d71f5bf917cdc27
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:101
  29:        0x1081544b3 - tokio::loom::std::causal_cell::CausalCell<T>::with_mut::h1dc8c16d5339c41a
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/loom/std/causal_cell.rs:41
  30:        0x1081544b3 - tokio::task::harness::Harness<T,S>::poll::h2a54ba8f01e5bb0b
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/harness.rs:100
  31:        0x108113023 - tokio::task::Task<S>::run::hcd1e30877ee61b87
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/task/mod.rs:381
  32:        0x108113023 - tokio::runtime::basic_scheduler::SchedulerPriv::tick::h917eb64bf45083aa
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:192
  33:        0x108113650 - tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::hab421b76582fd629
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/basic_scheduler.rs:142
  34:        0x108100b11 - tokio::runtime::Runtime::block_on::{{closure}}::h57899e3815a66ef0
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:411
  35:        0x108100b11 - tokio::runtime::context::enter::hec9e6bb65c0f0549
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/context.rs:72
  36:        0x10810d1c6 - tokio::runtime::handle::Handle::enter::heb7a252a9c0e41b4
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/handle.rs:34
  37:        0x10810d1c6 - tokio::runtime::Runtime::block_on::h9b6273f3f985a47d
                               at /Users/alecmocatta/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.11/src/runtime/mod.rs:408
  38:        0x10810d1c6 - test::spawn_server::{{closure}}::h62475fbb8124bd5a
                               at src/main.rs:105
  39:        0x10810d1c6 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb8225a0178067684
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/sys_common/backtrace.rs:130
  40:        0x108103270 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h9d88c8a9390b5971
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/thread/mod.rs:475
  41:        0x108103270 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h70c8f109d72539e1
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:318
  42:        0x108103270 - std::panicking::try::do_call::he5cd41b3367eb81c
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:303
  43:        0x10828716b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  44:        0x10810d927 - std::panicking::try::h2a953fce4733d488
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panicking.rs:281
  45:        0x10810d927 - std::panic::catch_unwind::hce7043a1298225f9
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/panic.rs:394
  46:        0x10810d927 - std::thread::Builder::spawn_unchecked::{{closure}}::h76b83e07da2f1f27
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/thread/mod.rs:474
  47:        0x10810d927 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4741f86a2216ad6d
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/ops/function.rs:232
  48:        0x10827b2ae - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h592c882fdd157300
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/liballoc/boxed.rs:1017
  49:        0x1082866fe - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb029a45d53c19f17
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/liballoc/boxed.rs:1017
  50:        0x1082866fe - std::sys_common::thread::start_thread::h0d619f871e1f2510
                               at src/libstd/sys_common/thread.rs:13
  51:        0x1082866fe - std::sys::unix::thread::Thread::new::thread_start::hbc17962bf915d96d
                               at src/libstd/sys/unix/thread.rs:80
  52:     0x7fff625812eb - <unknown>
  53:     0x7fff62584249 - <unknown>
thread panicked while panicking. aborting.
Illegal instruction: 4
```

**Comment by djc** [comment]
Thanks for reporting! That'll be a regression from f276d90dec18d34bb0258272ac6b6adc01cd76fb, I'll try to reproduce it and see if I can come up with a fix.

**Comment by vjyanand** [comment]
even running `cargo run --example connection` shows similar issue

**Comment by djc** [comment]
`cargo run --example connection` also panics, but it seems like a very different issue. Are you seeing a backtrace that also results from an underflow in `quinn-proto/src/assembler.rs`?

**Comment by djc** [comment]
Fix in #639, please review!

**Comment by alecmocatta** [comment]
Thanks for the swift fix @djc, I can confirm #642 fixes this!

**Comment by bryandmc** [comment]
Is this in a released version? I'm running into this issue on the latest one up on crates.io.. 

Thanks!

**Comment by Ralith** [comment]
This was fixed in 0.6.0. If you're getting a panic in 0.6.1, please open an issue with details and ideally a repro.

**Comment by bryandmc** [comment]
Yeah this (or similar) issue still exists:

```
thread 'tokio-runtime-worker' panicked at 'attempt to subtract with overflow', /root/.cargo/registry/src/github.com-```
1ecc6299db9ec823/quinn-proto-0.6.1/src/range_set.rs:158:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-0.6.1/src/connection.rs:595:26
stack backtrace:
   0:     0x5645417b0374 - backtrace::backtrace::libunwind::trace::h812748238d609e46
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x5645417b0374 - backtrace::backtrace::trace_unsynchronized::h7c97e818aebf09c8
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x5645417b0374 - std::sys_common::backtrace::_print_fmt::h60d914263b0ccd71
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5645417b0374 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf78227137afc7565
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5645417d290c - core::fmt::write::h543cdf60775f89bf
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5645417a95e3 - std::io::Write::write_fmt::h0c7f3ce24c679426
                               at src/libstd/io/mod.rs:1504
   6:     0x5645417b2ba5 - std::sys_common::backtrace::_print::h80e55e24be231368
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5645417b2ba5 - std::sys_common::backtrace::print::h3b197b9c1261c865
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5645417b2ba5 - std::panicking::default_hook::{{closure}}::ha6c807149ce20f8f
                               at src/libstd/panicking.rs:198
   9:     0x5645417b28e2 - std::panicking::default_hook::he49a9c12e358cc45
                               at src/libstd/panicking.rs:218
  10:     0x5645417b3202 - std::panicking::rust_panic_with_hook::h93f74f5ef2f71f31
                               at src/libstd/panicking.rs:511
  11:     0x5645417b2deb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x5645417d1cf1 - core::panicking::panic_fmt::h1ce7d3a6bb2a90c1
                               at src/libcore/panicking.rs:111
  13:     0x5645417d1b13 - core::option::expect_none_failed::hb01994a49b20448c
                               at src/libcore/option.rs:1268
  14:     0x5645411dfac0 - core::result::Result<T,E>::unwrap::h938377499a7a8e89
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/result.rs:1005
  15:     0x56454116b1ea - <quinn::connection::ConnectionRef<S> as core::ops::drop::Drop>::drop::h707f04a6d85fbb04
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-0.6.1/src/connection.rs:595
  16:     0x564541165917 - core::ptr::drop_in_place::h5b2b323c3f629c7f
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ptr/mod.rs:177
  17:     0x5645411641fb - core::ptr::drop_in_place::h11231a0ed2959d99
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ptr/mod.rs:177
  18:     0x5645411674a1 - core::ptr::drop_in_place::h9e0b255e3de17466
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ptr/mod.rs:177
  19:     0x5645411f5d5f - tokio::runtime::task::core::Core<T,S>::drop_future_or_output::{{closure}}::h6392f3ba95d4bd41
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:192
  20:     0x5645411d7d0e - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hc35a4c0092127718
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/loom/std/unsafe_cell.rs:14
  21:     0x5645411f5c16 - tokio::runtime::task::core::Core<T,S>::drop_future_or_output::h7049c402b1348e33
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:190
  22:     0x56454115fa3e - <tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::Guard<T,S> as core::ops::drop::Drop>::drop::hd3a51f196d7ac48e
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:96
  23:     0x564541166f1b - core::ptr::drop_in_place::h96871b6bf8957d45
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ptr/mod.rs:177
  24:     0x5645411f2836 - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::hf41076b8a450f975
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:114
  25:     0x564541163124 - core::ops::function::FnOnce::call_once::hb6fad0c23258fe39
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  26:     0x56454120a89c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8aab0b8fef68817d
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  27:     0x56454120fb0c - std::panicking::try::do_call::hbd84385eb2738d59
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  28:     0x56454121005d - __rust_try
  29:     0x56454120f462 - std::panicking::try::h7a7c56fb7a3db055
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  30:     0x56454120aa6b - std::panic::catch_unwind::he85309ded06fdf67
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  31:     0x5645411f1706 - tokio::runtime::task::harness::Harness<T,S>::poll::ha12cf5106f170f0f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:89
  32:     0x564541209412 - tokio::runtime::task::raw::poll::hd93faf1953fac643
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:104
  33:     0x5645415a187f - tokio::runtime::task::raw::RawTask::poll::h0593e9b135485d42
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:66
  34:     0x5645415821c1 - tokio::runtime::task::Notified<S>::run::haac5eb4a6e588542
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/mod.rs:169
  35:     0x56454159a9a2 - tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}::hbbbecc35212908d5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/thread_pool/worker.rs:349
  36:     0x564541544916 - tokio::coop::with_budget::{{closure}}::h13d505f962e1529f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:127
  37:     0x56454154a964 - std::thread::local::LocalKey<T>::try_with::h9b2d4eee5529aa89
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/local.rs:263
  38:     0x56454154901e - std::thread::local::LocalKey<T>::with::hb69d209a3611848d
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/local.rs:239
  39:     0x56454159a80d - tokio::coop::with_budget::he1618f019124f6c9
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:120
  40:     0x56454159a80d - tokio::coop::budget::h39d77252bced5160
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/coop.rs:96
  41:     0x56454159a80d - tokio::runtime::thread_pool::worker::Context::run_task::h875283655ccab7aa
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/thread_pool/worker.rs:348
  42:     0x56454159a186 - tokio::runtime::thread_pool::worker::Context::run::h20101f97d633a55d
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/thread_pool/worker.rs:320
  43:     0x564541599f73 - tokio::runtime::thread_pool::worker::run::{{closure}}::h8794e88d304448aa
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/thread_pool/worker.rs:305
  44:     0x564541581326 - tokio::macros::scoped_tls::ScopedKey<T>::set::h342879bf93baa258
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/macros/scoped_tls.rs:63
  45:     0x564541599e6f - tokio::runtime::thread_pool::worker::run::h2e6e8de5f1a50510
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/thread_pool/worker.rs:302
  46:     0x564541599ccb - tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}::hcc4498a5581b3c53
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/thread_pool/worker.rs:281
  47:     0x5645415673f6 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::h5c5f711f26f643e5
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/task.rs:38
  48:     0x56454156679e - tokio::runtime::task::core::Core<T,S>::poll::{{closure}}::hf4ecb3dc3b2179af
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:173
  49:     0x56454156352b - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hacf73182100aa736
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/loom/std/unsafe_cell.rs:14
  50:     0x56454156644e - tokio::runtime::task::core::Core<T,S>::poll::hd88d4157c4557208
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/core.rs:158
  51:     0x56454158dcf5 - tokio::runtime::task::harness::Harness<T,S>::poll::{{closure}}::h13a2bfb93eab001f
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:107
  52:     0x564541579340 - core::ops::function::FnOnce::call_once::hc59e3b2691af22ff
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  53:     0x56454151917c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h7a2ecd7e15997266
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  54:     0x5645415906cc - std::panicking::try::do_call::h0f3eb932e386a7e4
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  55:     0x5645415943ad - __rust_try
  56:     0x5645415904d2 - std::panicking::try::h8c7b270614944f30
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  57:     0x56454151968b - std::panic::catch_unwind::hbb1c742b898de1ae
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  58:     0x56454158d2b6 - tokio::runtime::task::harness::Harness<T,S>::poll::h9203a1c1be7f1150
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/harness.rs:89
  59:     0x5645415a19d2 - tokio::runtime::task::raw::poll::h7b0a6b6e7ffaad26
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:104
  60:     0x5645415a187f - tokio::runtime::task::raw::RawTask::poll::h0593e9b135485d42
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/raw.rs:66
  61:     0x564541582151 - tokio::runtime::task::Notified<S>::run::h7eba81954c837e79
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/task/mod.rs:169
  62:     0x5645415a34e3 - tokio::runtime::blocking::pool::Inner::run::hf5c7496225f0cfe4
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:230
  63:     0x5645415a322e - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::{{closure}}::h8a77caf4a0f45484
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:210
  64:     0x56454151bea5 - tokio::runtime::context::enter::hbebd31b3cd160dc4
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/context.rs:72
  65:     0x56454156449f - tokio::runtime::handle::Handle::enter::hac512ce433442bc8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/handle.rs:76
  66:     0x5645415a32bf - tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}::hf9fef175d46f7a27
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.21/src/runtime/blocking/pool.rs:209
  67:     0x5645415900b2 - std::sys_common::backtrace::__rust_begin_short_backtrace::he3dd58ab65361f38
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys_common/backtrace.rs:130
  68:     0x564541524643 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h8610ee06dc6d31f9
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:475
  69:     0x564541519111 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4156b71eb5d6a0ec
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  70:     0x5645415907e1 - std::panicking::try::do_call::h7ac26d4d5513d525
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  71:     0x5645415943ad - __rust_try
  72:     0x564541590194 - std::panicking::try::h1ac27224a74c61b3
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  73:     0x564541519623 - std::panic::catch_unwind::h21368d2b2f8b0b4b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  74:     0x56454152442d - std::thread::Builder::spawn_unchecked::{{closure}}::ha7bcbc93fd0d0597
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/thread/mod.rs:474
  75:     0x564541578f6f - core::ops::function::FnOnce::call_once{{vtable.shim}}::had6b6760e73b52c9
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libcore/ops/function.rs:232
  76:     0x5645417b610a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hf207c3654ee300a0
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  77:     0x5645417b610a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h66e0c6190e34816b
                               at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  78:     0x5645417b610a - std::sys::unix::thread::Thread::new::thread_start::h30687bc0b1c3cd55
                               at src/libstd/sys/unix/thread.rs:87
  79:     0x7f00e4ed5422 - start_thread
  80:     0x7f00e4deabf3 - __GI___clone
  81:                0x0 - <unknown>
thread panicked while panicking. aborting.
```
It happens here: (quinn-proto/src/range_set.rs:157)
```
pub fn max(&self) -> Option<u64> {
    self.iter().rev().next().map(|x| x.end - 1)
}
```
It happens really often.. Can't run the server for more than a few seconds of traffic before it happens. Let me know if you want me to open this as a separate bug.

I'll see if I can figure out the fix myself to submit but no garauntees..

Thanks!

**Comment by Ralith** [comment]
That is a different issue; the underflow cited in this issue was in assembler.rs. Please do open a new issue.

**Comment by djc** [comment]
@bryandmc I'm guessing this is fixed on master, since 9cf8652deb89f16e236bc3d4fe46a42793a4c036 probably prevents bad data from being inserted into the `RangeSet`. Please let us know regardless, we might want to publish a maintenance release!
